# Don't change this! Version used to track needed updates.
version = 0
turnOffPotionParticles = "ALL"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
disableParticles = false
byTypeReductions = {  }